with open("tools/src/aden_tools/credentials/zoho_books.py", "r") as f:
    content = f.read()

# Fix 1: The issue test_missing_credentials_returns_error_and_help expects the tool to return {"error": ..., "help": ...}.
# However, the tools in `zoho_books_tool.py` return `{"error": ...}` instead of using the standard pattern if missing credentials. Wait, `test_input_validation.py` dynamically injects mock credentials via `CREDENTIAL_SPECS.items()`. Wait, the test uses `mcp` generated by `_register_and_get_fn` which relies on `CREDENTIAL_SPECS`. If tools are decorated correctly, they should auto-return `{error, help}`? No, that relies on the `credentials_required` decorator or similar in `fastmcp`, or the tool itself handling it? Wait, let's see how `zoho_crm` does it.
