"""
Static graph analyzer for pre-execution validation.
"""

from collections import defaultdict
from dataclasses import dataclass
from enum import StrEnum

from framework.graph.edge import GraphSpec


class Severity(StrEnum):
    """Severity level of an analysis issue."""

    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


@dataclass
class AnalysisIssue:
    """An issue found during graph analysis."""

    severity: Severity
    message: str
    node_id: str | None = None


@dataclass
class AnalysisReport:
    """Report generated by static graph analysis."""

    issues: list[AnalysisIssue]
    token_estimate: int

    @property
    def errors(self) -> list[AnalysisIssue]:
        return [i for i in self.issues if i.severity == Severity.ERROR]

    @property
    def warnings(self) -> list[AnalysisIssue]:
        return [i for i in self.issues if i.severity == Severity.WARNING]

    @property
    def infos(self) -> list[AnalysisIssue]:
        return [i for i in self.issues if i.severity == Severity.INFO]

    def passed(self) -> bool:
        """Returns True if no errors were found."""
        return len(self.errors) == 0


class GraphAnalyzer:
    """
    Performs comprehensive static analysis on agent graphs before runtime.

    Detects structural issues like dangerous cycles, unreachable nodes,
    missing inputs, dead-end paths, and key collisions.
    """

    LLM_NODE_TYPES = {"event_loop", "gcu", "llm"}
    TOKENS_PER_LLM_NODE = 800

    def __init__(self, graph: GraphSpec):
        self.graph = graph
        self.nodes = {node.id: node for node in self.graph.nodes}

        # Build adjacency lists
        self.outgoing_edges = defaultdict(list)
        self.incoming_edges = defaultdict(list)
        for edge in self.graph.edges:
            self.outgoing_edges[edge.source].append(edge)
            self.incoming_edges[edge.target].append(edge)

    def analyze(self) -> AnalysisReport:
        """Run all static analysis checks."""
        issues = []

        # Determine reachable nodes from entry point(s)
        reachable_nodes = self._get_reachable_nodes()

        # Check Unreachable nodes
        issues.extend(self._check_unreachable_nodes(reachable_nodes))

        # Check Dead-end paths
        issues.extend(self._check_dead_end_paths(reachable_nodes))

        # Check Cycles
        issues.extend(self._check_cycles(reachable_nodes))

        # Check Missing inputs and Output key collisions
        path_issues = self._check_data_flow(reachable_nodes)
        issues.extend(path_issues)

        # Estimate token cost
        token_cost = self._estimate_token_cost(reachable_nodes)

        return AnalysisReport(issues=issues, token_estimate=token_cost)

    def _get_reachable_nodes(self) -> set[str]:
        """Find all nodes reachable from entry points using BFS."""
        reachable = set()
        queue = []

        if self.graph.entry_node in self.nodes:
            queue.append(self.graph.entry_node)

        for ep_node in self.graph.entry_points.values():
            if ep_node in self.nodes and ep_node not in queue:
                queue.append(ep_node)

        while queue:
            current = queue.pop(0)
            if current not in reachable:
                reachable.add(current)
                for edge in self.outgoing_edges.get(current, []):
                    if edge.target in self.nodes and edge.target not in reachable:
                        queue.append(edge.target)

        return reachable

    def _check_unreachable_nodes(self, reachable: set[str]) -> list[AnalysisIssue]:
        """Detect nodes that can never be reached."""
        issues = []
        for node_id in self.nodes:
            if node_id not in reachable:
                issues.append(
                    AnalysisIssue(
                        severity=Severity.WARNING,
                        message=f"Node '{node_id}' is unreachable.",
                        node_id=node_id,
                    )
                )
        return issues

    def _check_dead_end_paths(self, reachable: set[str]) -> list[AnalysisIssue]:
        """Detect non-terminal reachable nodes with no outgoing edges."""
        issues = []
        terminal_nodes = set(self.graph.terminal_nodes)

        for node_id in reachable:
            if node_id not in terminal_nodes and not self.outgoing_edges.get(node_id):
                issues.append(
                    AnalysisIssue(
                        severity=Severity.ERROR,
                        message=f"Dead-end path at node '{node_id}'. "
                        "Not a terminal node but has no outgoing edges.",
                        node_id=node_id,
                    )
                )
        return issues

    def _check_cycles(self, reachable: set[str]) -> list[AnalysisIssue]:
        """Detect dangerous cycles (where max_node_visits is 0/unlimited)."""
        issues = []
        visited = set()
        path = set()

        def dfs(node_id: str):
            if node_id in path:
                # Cycle detected
                node = self.nodes.get(node_id)
                if node:
                    max_visits = getattr(node, "max_node_visits", 0)
                    if max_visits == 0:
                        issues.append(
                            AnalysisIssue(
                                severity=Severity.ERROR,
                                message=f"Dangerous cycle detected at node '{node_id}' "
                                "with max_node_visits=0.",
                                node_id=node_id,
                            )
                        )
                return
            if node_id in visited:
                return

            visited.add(node_id)
            path.add(node_id)
            for edge in self.outgoing_edges.get(node_id, []):
                if edge.target in reachable:
                    dfs(edge.target)
            path.remove(node_id)

        for node in reachable:
            if node not in visited:
                dfs(node)

        # Deduplicate cycle issues (since multiple edges could find the same cycle)
        unique_issues = []
        seen = set()
        for i in issues:
            if i.message not in seen:
                seen.add(i.message)
                unique_issues.append(i)

        return unique_issues

    def _check_data_flow(self, reachable: set[str]) -> list[AnalysisIssue]:
        """
        Detect missing inputs and output key collisions using BFS.
        Tracks available keys and writers along execution paths.
        """
        issues = []

        starts = []
        if self.graph.entry_node in self.nodes:
            starts.append(self.graph.entry_node)
        for ep in self.graph.entry_points.values():
            if ep in self.nodes and ep not in starts:
                starts.append(ep)

        # queue elements: (current_node_id, available_keys_set)
        queue = [(start, frozenset()) for start in starts]
        visited_states = set()

        while queue:
            current, available_keys = queue.pop(0)

            state = (current, available_keys)
            if state in visited_states:
                continue
            visited_states.add(state)

            node = self.nodes[current]

            # Check inputs
            req_keys = getattr(node, "input_keys", [])
            for req_key in req_keys:
                if req_key not in available_keys:
                    issues.append(
                        AnalysisIssue(
                            severity=Severity.ERROR,
                            message=f"Missing input key '{req_key}' for node '{current}'.",
                            node_id=current,
                        )
                    )

            # Check collisions and update keys
            new_keys = set(available_keys)
            out_keys = getattr(node, "output_keys", [])
            for out_key in out_keys:
                if out_key in available_keys:
                    issues.append(
                        AnalysisIssue(
                            severity=Severity.WARNING,
                            message=f"Output key collision for '{out_key}' at node '{current}'.",
                            node_id=current,
                        )
                    )
                new_keys.add(out_key)

            new_keys_frozen = frozenset(new_keys)

            # Propagate to targets
            for edge in self.outgoing_edges.get(current, []):
                if edge.target in reachable:
                    queue.append((edge.target, new_keys_frozen))

        # Deduplicate issues
        unique_issues = []
        seen_msgs = set()
        for i in issues:
            if i.message not in seen_msgs:
                seen_msgs.add(i.message)
                unique_issues.append(i)

        return unique_issues

    def _estimate_token_cost(self, reachable: set[str]) -> int:
        """Estimate token cost based on LLM node count."""
        count = 0
        for node_id in reachable:
            node = self.nodes.get(node_id)
            if node and getattr(node, "node_type", "") in self.LLM_NODE_TYPES:
                # If node has max_node_visits > 0, we could multiply by it
                # but an approximation is fine
                visits = getattr(node, "max_node_visits", 1)
                if visits == 0:
                    visits = 1
                count += visits
        return count * self.TOKENS_PER_LLM_NODE
