
import React, { useState } from 'react';
import { FileText, Code, Copy, Check, Download, ExternalLink, Terminal } from 'lucide-react';
import MarkdownView from './MarkdownView';

interface Artifact {
  id: string;
  type: string;
  title: string;
  content: string;
}

interface ArtifactViewProps {
  artifact: Artifact;
}

/**
 * Enhanced viewer for artifacts generated by Hive agents.
 * 
 * Supports different rendering modes for Markdown and Python code,
 * providing a premium, structured visual experience.
 * 
 * @param {ArtifactViewProps} props Component properties.
 * @returns {React.ReactElement} The rendered artifact view.
 */
const ArtifactView: React.FC<ArtifactViewProps> = ({ artifact }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(artifact.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const renderContent = () => {
    if (artifact.type === 'python' || artifact.type === 'code') {
      return (
        <div className="relative font-mono text-[13px] bg-black/40 rounded-xl border border-white/5 overflow-hidden group/code">
          <div className="flex items-center justify-between px-4 py-2 bg-white/5 border-b border-white/5">
             <div className="flex items-center gap-2">
                <Terminal size={14} className="text-secondary" />
                <span className="text-[10px] font-bold text-muted uppercase tracking-widest">source.py</span>
             </div>
             <button 
               onClick={handleCopy}
               className="p-1.5 hover:bg-white/10 rounded-md transition-colors text-muted hover:text-white"
               title="Copy Code"
             >
               {copied ? <Check size={14} className="text-success" /> : <Copy size={14} />}
             </button>
          </div>
          <div className="p-4 overflow-x-auto custom-scrollbar leading-relaxed">
            {artifact.content.split('\n').map((line, i) => (
              <div key={i} className="flex gap-4 group/line">
                <span className="w-8 text-right text-muted/30 select-none">{i + 1}</span>
                <span className="text-slate-300 whitespace-pre">{highlightPython(line)}</span>
              </div>
            ))}
          </div>
        </div>
      );
    }

    // Use the premium MarkdownView for all non-code artifacts
    return (
      <div className="bg-black/20 rounded-xl border border-white/5 p-4 prose prose-invert max-w-none">
        <MarkdownView content={artifact.content} />
      </div>
    );
  };

  return (
    <div className="artifact-card group">
      <div className="artifact-header mb-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className={`p-3 rounded-2xl ${artifact.type === 'python' ? 'bg-secondary/10' : 'bg-primary/10'}`}>
              {artifact.type === 'python' ? <Code className="text-secondary" /> : <FileText className="text-primary" />}
            </div>
            <div>
              <h4 className="text-lg font-bold text-white group-hover:text-primary transition-colors">{artifact.title}</h4>
              <div className="flex items-center gap-2 mt-1">
                <span className="text-[10px] font-black uppercase text-muted tracking-widest bg-white/5 px-2 py-0.5 rounded">{artifact.type}</span>
                <span className="text-[10px] text-muted opacity-50">•</span>
                <span className="text-[10px] text-muted uppercase tracking-widest">{artifact.content.length} bytes</span>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button className="action-btn" onClick={handleCopy}>
              {copied ? <Check size={16} className="text-success" /> : <Copy size={16} />}
            </button>
            <button className="action-btn">
              <Download size={16} />
            </button>
            <button className="action-btn">
              <ExternalLink size={16} />
            </button>
          </div>
        </div>
      </div>
      
      <div className="artifact-body">
        {renderContent()}
      </div>

      <style>{`
        .artifact-card {
          padding: 2rem;
          background: var(--bg-surface);
          border-radius: var(--border-radius-lg);
          border: 1px solid var(--glass-border);
          transition: all var(--transition-smooth);
          position: relative;
          overflow: hidden;
          box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        }
        .artifact-card:hover {
          border-color: var(--primary-glow);
          transform: translateY(-2px);
          box-shadow: 0 20px 40px rgba(0,0,0,0.4);
        }
        .action-btn {
          width: 36px;
          height: 36px;
          border-radius: 10px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: rgba(255,255,255,0.03);
          border: 1px solid var(--glass-border);
          color: var(--text-muted);
          cursor: pointer;
          transition: all 0.2s;
        }
        .action-btn:hover {
          background: rgba(255,255,255,0.08);
          color: #fff;
          border-color: var(--primary);
        }
        .custom-scrollbar::-webkit-scrollbar {
          height: 6px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: transparent;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: rgba(255,255,255,0.1);
          border-radius: 10px;
        }
      `}</style>
    </div>
  );
};

/**
 * Basic syntax highlighting for Python code.
 * 
 * @param {string} code The code line to highlight.
 * @returns {React.ReactNode} The highlighted code.
 */
function highlightPython(code: string) {
  if (!code) return '';
  
  const keywords = /\b(def|class|if|else|elif|for|while|return|import|from|as|try|except|finally|with|in|is|not|and|or|lambda|async|await)\b/g;
  const builtins = /\b(print|range|len|int|str|list|dict|set|tuple|enumerate|zip|sum|max|min|abs|round)\b/g;
  const strings = /(['"])(.*?)\1/g;
  const comments = /#.*$/g;
  const decorators = /@\w+/g;
  const functions = /\b\w+(?=\()/g;

  let highlighted = code
    .replace(strings, '<span class="text-success">$0</span>')
    .replace(comments, '<span class="text-muted italic">$0</span>')
    .replace(keywords, '<span class="text-primary font-bold">$0</span>')
    .replace(builtins, '<span class="text-secondary">$0</span>')
    .replace(decorators, '<span class="text-warning">$0</span>')
    .replace(functions, '<span class="text-info font-medium">$0</span>');

  return <span dangerouslySetInnerHTML={{ __html: highlighted }} />;
}

export default ArtifactView;
