edges = [
    {
        "edge_id": "intake-to-list-projects",
        "source": "intake",
        "target": "list_projects",
        "condition": "on_success",
        "priority": 1,
    },
    {
        "edge_id": "list-projects-to-manage-issues",
        "source": "list_projects",
        "target": "manage_issues",
        "condition": "on_success",
        "priority": 1,
    },
    {
        "edge_id": "manage-issues-to-manage-mr",
        "source": "manage_issues",
        "target": "manage_mr",
        "condition": "on_success",
        "priority": 1,
    },
    {
        "edge_id": "manage-mr-to-manage-pipelines",
        "source": "manage_mr",
        "target": "manage_pipelines",
        "condition": "on_success",
        "priority": 1,
    },
    {
        "edge_id": "manage-pipelines-to-respond",
        "source": "manage_pipelines",
        "target": "respond",
        "condition": "on_success",
        "priority": 1,
    },
    {
        "edge_id": "intake-to-respond-error",
        "source": "intake",
        "target": "respond",
        "condition": "on_failure",
        "priority": -1,
    },
    {
        "edge_id": "list-projects-to-respond-error",
        "source": "list_projects",
        "target": "respond",
        "condition": "on_failure",
        "priority": -1,
    },
    {
        "edge_id": "manage-issues-to-respond-error",
        "source": "manage_issues",
        "target": "respond",
        "condition": "on_failure",
        "priority": -1,
    },
    {
        "edge_id": "manage-mr-to-respond-error",
        "source": "manage_mr",
        "target": "respond",
        "condition": "on_failure",
        "priority": -1,
    },
    {
        "edge_id": "manage-pipelines-to-respond-error",
        "source": "manage_pipelines",
        "target": "respond",
        "condition": "on_failure",
        "priority": -1,
    },
]
