import pytest

from framework.graph.goal import Goal
from framework.runtime.outcome_aggregator import OutcomeAggregator
from framework.schemas.kpi import KPI, KPICalculationMethod


@pytest.fixture
def sample_goal():
    """Create a basic goal with KPIs for testing."""
    return Goal(
        id="test-goal-kpi",
        name="Test Goal KPI",
        description="A goal with business KPIs",
        kpis=[
            KPI(
                id="revenue",
                name="Revenue Generated",
                description="Total revenue generated by the agent.",
                target=100.0,
                calculation_method=KPICalculationMethod.SUM,
            ),
            KPI(
                id="csat",
                name="Customer Satisfaction",
                description="Average CSAT score.",
                target=4.0,
                calculation_method=KPICalculationMethod.AVERAGE,
            ),
            KPI(
                id="leads",
                name="Leads Created",
                description="Total number of leads created.",
                target=5.0,
                calculation_method=KPICalculationMethod.COUNT,
            ),
            KPI(
                id="status",
                name="System Status",
                description="Latest system status score.",
                target=1.0,
                calculation_method=KPICalculationMethod.LATEST,
            ),
        ],
    )


@pytest.mark.asyncio
async def test_kpi_evaluation_sum(sample_goal):
    """Test KPI evaluation using the SUM calculation method."""
    aggregator = OutcomeAggregator(goal=sample_goal)

    # Record some revenue metrics
    aggregator.record_kpi_metric("revenue", 50.0, "node_1")
    aggregator.record_kpi_metric("revenue", 60.0, "node_2")

    evaluations = await aggregator.evaluate_kpis()

    # Find the revenue KPI evaluation
    revenue_eval = next((e for e in evaluations if e.kpi_id == "revenue"), None)

    assert revenue_eval is not None
    assert revenue_eval.current_value == 110.0
    assert revenue_eval.is_meeting_target is True
    assert revenue_eval.trend == "up"


@pytest.mark.asyncio
async def test_kpi_evaluation_average(sample_goal):
    """Test KPI evaluation using the AVERAGE calculation method."""
    aggregator = OutcomeAggregator(goal=sample_goal)

    # Record CSAT metrics
    aggregator.record_kpi_metric("csat", 5.0, "node_1")
    aggregator.record_kpi_metric("csat", 3.0, "node_2")
    aggregator.record_kpi_metric("csat", 4.0, "node_3")

    evaluations = await aggregator.evaluate_kpis()

    csat_eval = next((e for e in evaluations if e.kpi_id == "csat"), None)

    assert csat_eval is not None
    assert csat_eval.current_value == 4.0
    assert csat_eval.is_meeting_target is True
    assert csat_eval.trend == "down"


@pytest.mark.asyncio
async def test_kpi_evaluation_count(sample_goal):
    """Test KPI evaluation using the COUNT calculation method."""
    aggregator = OutcomeAggregator(goal=sample_goal)

    # Record leads
    aggregator.record_kpi_metric("leads", 1.0, "node_1")
    aggregator.record_kpi_metric("leads", 1.0, "node_2")
    aggregator.record_kpi_metric("leads", 1.0, "node_3")

    evaluations = await aggregator.evaluate_kpis()

    leads_eval = next((e for e in evaluations if e.kpi_id == "leads"), None)

    assert leads_eval is not None
    assert leads_eval.current_value == 3.0
    assert leads_eval.is_meeting_target is False
    assert leads_eval.trend == "stable"


@pytest.mark.asyncio
async def test_kpi_evaluation_latest(sample_goal):
    """Test KPI evaluation using the LATEST calculation method."""
    aggregator = OutcomeAggregator(goal=sample_goal)

    # Record system status
    aggregator.record_kpi_metric("status", 0.5, "node_1")
    # Small sleep to ensure different timestamps if testing locally
    import asyncio

    await asyncio.sleep(0.01)
    aggregator.record_kpi_metric("status", 1.2, "node_2")
    await asyncio.sleep(0.01)
    aggregator.record_kpi_metric("status", 0.9, "node_3")

    evaluations = await aggregator.evaluate_kpis()

    status_eval = next((e for e in evaluations if e.kpi_id == "status"), None)

    assert status_eval is not None
    assert status_eval.current_value == 0.9
    assert status_eval.is_meeting_target is False


@pytest.mark.asyncio
async def test_goal_progress_includes_kpis(sample_goal):
    """Test that evaluate_goal_progress includes KPI evaluations."""
    aggregator = OutcomeAggregator(goal=sample_goal)

    aggregator.record_kpi_metric("revenue", 120.0, "node_1")

    progress = await aggregator.evaluate_goal_progress()

    assert "kpi_evaluations" in progress

    evaluations = progress["kpi_evaluations"]
    assert len(evaluations) > 0

    revenue_eval = next((e for e in evaluations if e["kpi_id"] == "revenue"), None)
    assert revenue_eval is not None
    assert revenue_eval["current_value"] == 120.0
    assert revenue_eval["is_meeting_target"] is True


def test_aggregator_stats_includes_kpis(sample_goal):
    """Test that get_stats includes KPI metrics count."""
    aggregator = OutcomeAggregator(goal=sample_goal)

    aggregator.record_kpi_metric("revenue", 120.0, "node_1")

    stats = aggregator.get_stats()
    assert "kpi_metrics_recorded" in stats
    assert stats["kpi_metrics_recorded"] == 1
